ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM ${BASE_CONTAINER}

USER root

RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    curl \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN conda install --quiet --yes -c conda-forge \
    'ipywidgets=7.4.2' \
    'beakerx=1.4.1' \
    'kafka-python=1.4.7' \
    'jupyter_contrib_nbextensions=0.5.1' \
    && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

RUN beakerx install

RUN jupyter contrib nbextension install 

USER $NB_UID
